on:
  workflow_dispatch:
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build container
        run: podman build -t ghcr.io/megane-vilain/panda_bot:latest -f Containerfile .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push container
        run: podman push ghcr.io/megane-vilain/panda_bot:latest

